/**
 * CSIC AI Platform — JSX Pre-Compiler
 * Extracts <script type="text/babel"> from Jinja2 templates,
 * transpiles with Babel standalone, saves as static JS files.
 * 
 * Run: node scripts/compile.js
 */
const fs = require('fs');
const path = require('path');
const babel = require('../static/lib/babel.min.js');

const BASE = path.resolve(__dirname, '..');
const TEMPLATES = path.join(BASE, 'templates');
const OUTPUT = path.join(BASE, 'static', 'js', 'pages');

// Template → output JS file mapping
const PAGES = [
  ['public/landing.html',  'landing'],
  ['public/login.html',    'login'],
  ['chat.html',            'chat'],
  ['workspace/teaching.html', 'teaching'],
  ['workspace/research.html', 'research'],
  ['workspace/news.html',     'news'],
  ['workspace/skills.html',   'skills'],
  ['workspace/video.html',    'video'],
  ['workspace/admin.html',    'admin'],
  ['workspace/knowledge.html','knowledge'],
];

function extractJSX(filePath) {
  let content = fs.readFileSync(filePath, 'utf-8');
  
  // Remove Jinja2 {% raw %} and {% endraw %} tags
  content = content.replace(/\{%\s*raw\s*%\}/g, '');
  content = content.replace(/\{%\s*endraw\s*%\}/g, '');
  
  // Find <script type="text/babel"> ... </script>
  const match = content.match(/<script\s+type=["']text\/babel["'][^>]*>([\s\S]*?)<\/script>/);
  if (!match) return null;
  
  return match[1].trim();
}

function compileJSX(jsx, pageName) {
  // Add React import handling: the code uses globals (React, antd, AntDesignIcons)
  // We need to add a hint for eslint-like tools, but Babel doesn't need this
  try {
    const result = babel.transform(jsx, {
      presets: [['react', { runtime: 'classic' }]],
      filename: pageName + '.jsx',
    });
    return result.code;
  } catch (e) {
    console.error(`  [ERR] ${pageName}: ${e.message}`);
    return null;
  }
}

function main() {
  console.log('CSIC AI Platform — JSX Pre-Compiler');
  console.log('='.repeat(50));
  
  // Ensure output dir exists
  if (!fs.existsSync(OUTPUT)) {
    fs.mkdirSync(OUTPUT, { recursive: true });
  }
  
  let success = 0;
  let fail = 0;
  
  for (const [relPath, name] of PAGES) {
    const fullPath = path.join(TEMPLATES, relPath);
    console.log(`\n[${name}] ${relPath}`);
    
    if (!fs.existsSync(fullPath)) {
      console.log(`  [SKIP] File not found`);
      continue;
    }
    
    const jsx = extractJSX(fullPath);
    if (!jsx) {
      console.log(`  [SKIP] No <script type="text/babel"> found`);
      continue;
    }
    
    console.log(`  JSX: ${jsx.length} chars`);
    
    const compiled = compileJSX(jsx, name);
    if (!compiled) {
      fail++;
      continue;
    }
    
    const outFile = path.join(OUTPUT, name + '.js');
    const header = `/**
 * CSIC AI Platform — ${name}.js
 * AUTO-GENERATED from ${relPath}. Do not edit directly.
 * Generated by scripts/compile.js
 */
`;
    fs.writeFileSync(outFile, header + compiled, 'utf-8');
    
    const sizeKB = (fs.statSync(outFile).size / 1024).toFixed(1);
    console.log(`  [OK] ${sizeKB}KB → static/js/pages/${name}.js`);
    success++;
  }
  
  console.log(`\n${'='.repeat(50)}`);
  console.log(`Result: ${success} OK, ${fail} fail`);
}

main();
